// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwoawzxzddxjdkxnzjjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3b2F3enh6ZGR4amRreG56ampnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzczNDQsImV4cCI6MjA2NjcxMzM0NH0.5cu43ZRH4JW3W16XDuSdFtWtIRBRff9GbmcFcRovXik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);